<a href="https://colab.research.google.com/github/AdityaKadam369/DSPY-LAB_EXPERIMENTs/blob/main/Notebook1_DataSelection_Cleaning_2301618.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Notebook01: Data Selection and Data Cleaning**

##**Aim: To perform data loading, inspection, and cleaning.**

In [ ]:
import pandas as pd
import numpy as np

**Data Selection:**

Data selection is the process of choosing a relevant dataset for analysis.
For this project, the Teen Mental Health Dataset is selected because it contains information related to students' mental health, lifestyle, and social factors. This dataset is useful for understanding patterns affecting teen mental well-being

**Data Loading:**

The dataset is loaded into the notebook using the Python library pandas.
This step converts the CSV file into a structured dataframe format which allows easy manipulation and analysis.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Teen_Mental_Health_Dataset.csv to Teen_Mental_Health_Dataset.csv

In [ ]:
import pandas as pd
df = pd.read_csv('Teen_Mental_Health_Dataset.csv')
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

**Data Inspection:**

After loading the dataset, the first few rows are displayed using `head()` function.
This helps to:

Understand column names
View sample data
Verify successful loading

In [ ]:
df.shape

(1200, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

**Understanding Dataset Structure:**

The `shape()` and `info()` functions are used to understand:

◾ Number of rows and columns

◾ Data types of each attribute

◾ Non-null values

This step provides a basic overview of the dataset.

In [ ]:
df.describe()

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,15.928333,4.536667,6.449417,1.740333,2.990383,1.014500,5.445833,5.636667,5.565000,0.025833
std,2.021947,2.029599,1.442677,0.716660,0.576758,0.582185,2.903290,2.859453,2.830627,0.158704
min,13.000000,1.000000,4.000000,0.500000,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,14.000000,2.800000,5.200000,1.100000,2.500000,0.500000,3.000000,3.000000,3.000000,0.000000
50%,16.000000,4.500000,6.500000,1.800000,2.990000,1.000000,5.000000,6.000000,6.000000,0.000000
75%,18.000000,6.300000,7.600000,2.400000,3.480000,1.500000,8.000000,8.000000,8.000000,0.000000
max,19.000000,8.000000,9.000000,3.000000,4.000000,2.000000,10.000000,10.000000,10.000000,1.000000

**Statistical Summary:**

The `describe()` function is used to generate summary statistics such as:

◾ Mean

◾ Standard deviation

◾ Minimum and maximum values

◾ Quartiles

This helps to understand distribution of numerical attributes.

In [ ]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

**Checking Missing Values:**

Missing values can affect analysis accuracy.
The `isnull().sum()` function is used to identify null values in each column.

In [ ]:
df.dtypes

age                           int64
gender                       object
daily_social_media_hours    float64
platform_usage               object
sleep_hours                 float64
screen_time_before_sleep    float64
academic_performance        float64
physical_activity           float64
social_interaction_level     object
stress_level                  int64
anxiety_level                 int64
addiction_level               int64
depression_label              int64
dtype: object

**Data Cleaning:**

Data cleaning is performed to improve dataset quality.
The following operations are performed:

◾ Removing missing values

◾ Handling inconsistent data

◾ Removing unnecessary entries

This ensures dataset reliability

**Checking Data Types:**

Each column's data type is verified using `dtypes.`
Correct data types ensure proper statistical analysis and visualization.

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop_duplicates()
df.shape

(1200, 13)

**Removing Duplicate Records:**

Duplicate records may bias the results.
The `drop_duplicates()` function is used to remove duplicate rows.

In [ ]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='object')

**Saving Cleaned Dataset:**

After cleaning, the processed dataset is saved as a new CSV file.

This cleaned dataset will be used in Notebook 2 for Exploratory Data Analysis.

In [ ]:
df.to_csv('Teen_Mental_Health_Cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download("Teen_Mental_Health_Cleaned.csv")

In [ ]:
import os
os.listdir()

['.config',
 'Teen_Mental_Health_Dataset.csv',
 'Teen_Mental_Health_Cleaned.csv',
 'sample_data']

**Conclusion:**

The dataset was successfully loaded and cleaned. Missing values and duplicates were handled. The dataset is now ready for further analysis.